# version: '1'

# networks:
#   app-tier:
#     driver: bridge

# services:
#   rabbitmq:
#     image: rabbitmq:latest
#     container_name: rabbitmq
#     hostname: rabbitmq
#     volumes:
#       - /var/lib/rabbitmq
#     networks:
#       - app-tier
#     ports:
#       - "5672:5672"
#       - "15672:15672"
#     env_file:
#       - .env

# version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env

networks:
  default:
    driver: bridge
